### ISSUE TITLE
Reduce the lib size

### ISSUE THREAD

**Issue by jeco123** [kamranahmedse/redux-persist-expire#2]
Hi,
Thanks for your work :-). I suggest to reduce the lib size due to the use of the 'moment' lib. Please, date-fns could be interesting in your case.

have a nice day :-)

Jérôme

**Comment by pungggi** [comment]
yes, same advice 
![grafik](https://user-images.githubusercontent.com/5635709/56955152-deb51880-6b40-11e9-8ac9-252321ddef43.png)

**Comment by sandinosaso** [comment]
I created a PR to remove moment dependency https://github.com/kamranahmedse/redux-persist-expire/pull/8

**Comment by sandinosaso** [comment]
I think @pungggi you will be happy :)
<img width="821" alt="Screen Shot 2019-05-21 at 1 48 38 PM" src="https://user-images.githubusercontent.com/466105/58118598-35a58f00-7bcf-11e9-997d-8f8f0f1fd6d1.png">

**Comment by jeco123** [comment]
Waou good job @sandinosaso!

**Comment by sandinosaso** [comment]
Thanks, @jeco123 It was not that much hard is just on file with 2 big functions that need to be changed very little.
I hope @kamranahmedse agree to merge this but in the meanwhile, if you need the change you can install from a branch using:
`yarn add https://github.com/sandinosaso/redux-persist-expire.git#feature/RemoveMoment`
When the branch is merged you need to change your package.json to point again to the library from npm. Could be useful for trying in the meanwhile

**Comment by kamranahmedse** [comment]
This has been released in [1.1.0](https://github.com/kamranahmedse/redux-persist-expire/releases/tag/1.1.0). Than you @sandinosaso.
