### ISSUE TITLE
it's did't work

### ISSUE THREAD

**Issue by zhangwei900808** [kamranahmedse/redux-persist-expire#7]
I used redux-persist-expire,but when I refresh the localstorage it did not work ,which is wrong!
```
const persistConfig = {
  transforms: [
    // encryptor,
    expireReducer("authReducer", {
      expireSeconds: 10
    })
  ],
  key: config.persist,
  storage,
  version: 2,
  migrate: createMigrate(migrations, { debug: false })
};

const finalReducer = persistReducer(persistConfig, createRootReducer(history));
```
![image](https://user-images.githubusercontent.com/4385154/57498573-e463e880-730e-11e9-9f58-f7251195fdb0.png)

**Comment by kamranahmedse** [comment]
You need to pass `autoExpire: true` as an option  to the `expireReducer`. Try changing the `expireReducer` options to be like below

```javascript
      expireReducer('authReducer', {
        expireSeconds: 10,
        autoExpire: true
      })
```

**Comment by zhangwei900808** [comment]
@kamranahmedse 
thanks your resolve my problem :)
but when I used encryptor that localstorage data is error and while you refresh the brower is always  lost authReducer ,you can see below code
```
import createEncryptor from "redux-persist-transform-encrypt";
import expireReducer from "redux-persist-expire";

const encryptor = createEncryptor({
  secretKey: "hiynn",
  onError: function(error) {}
});

const expireTransform = expireReducer("authReducer", {
  expireSeconds: 10,
  expiredState: {},
  autoExpire: true
});

const persistConfig = {
  transforms: [
    encryptor,
    expireTransform
  ],
  key: config.persist,
  storage,
  version: 2,
  migrate: createMigrate(migrations, { debug: false })
};

```
![image](https://user-images.githubusercontent.com/4385154/58065355-fe77b380-7bb7-11e9-8f42-5c6728bc51ae.png)
